/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsales;

/**
 *
 * @author shieda
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        mainPanel.setEnabled(false);
        mainPanel.setVisible(false);
        pack();
    }
    
    public void closeMainPanel(){
        mainPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new pointofsales.MainPanel();
        menuBar = new javax.swing.JMenuBar();
        newTransactionButton = new javax.swing.JMenu();
        transactionsButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 675));

        mainPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                mainPanelComponentHidden(evt);
            }
        });
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        newTransactionButton.setText("New Transaction");
        newTransactionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newTransactionButtonMouseClicked(evt);
            }
        });
        menuBar.add(newTransactionButton);

        transactionsButton.setText("Transactions");
        menuBar.add(transactionsButton);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTransactionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTransactionButtonMouseClicked
        if (!mainPanel.isVisible()) {
            Transaction transaction = new Transaction();
            mainPanel.setTransaction(transaction);
            mainPanel.setEnabled(true);
            mainPanel.setVisible(true);
            newTransactionButton.setEnabled(false);
            pack();
            mainPanel.itemSearchRequestFocus();
        }

    }//GEN-LAST:event_newTransactionButtonMouseClicked

    private void mainPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mainPanelComponentHidden
        newTransactionButton.setEnabled(true);
    }//GEN-LAST:event_mainPanelComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pointofsales.MainPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu newTransactionButton;
    private javax.swing.JMenu transactionsButton;
    // End of variables declaration//GEN-END:variables
}
