/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsales;

/**
 *
 * @author shieda
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        mainPanel.setEnabled(false);
        mainPanel.setVisible(false);
        pack();
    }

    public void closeMainPanel() {
        mainPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new pointofsales.MainPanel();
        menuBar = new javax.swing.JMenuBar();
        transactionsButton = new javax.swing.JMenu();
        newTransactionMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        productsMenuItem = new javax.swing.JMenuItem();
        addProductMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 675));

        mainPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                mainPanelComponentHidden(evt);
            }
        });
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        transactionsButton.setText("Transaction");

        newTransactionMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        newTransactionMenu.setText("New Transaction");
        newTransactionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransactionMenuActionPerformed(evt);
            }
        });
        transactionsButton.add(newTransactionMenu);

        jMenuItem1.setText("View Transactions");
        transactionsButton.add(jMenuItem1);

        menuBar.add(transactionsButton);

        jMenu1.setText("Product");

        productsMenuItem.setText("Products");
        productsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(productsMenuItem);

        addProductMenuItem.setText("Add Product");
        addProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addProductMenuItem);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mainPanelComponentHidden
        newTransactionMenu.setEnabled(true);
    }//GEN-LAST:event_mainPanelComponentHidden

    private void newTransactionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransactionMenuActionPerformed
        if (!mainPanel.isVisible()) {
            Transaction transaction = new Transaction();
            mainPanel.setTransaction(transaction);
            mainPanel.setEnabled(true);
            mainPanel.setVisible(true);
            newTransactionMenu.setEnabled(false);
            pack();
            mainPanel.itemSearchRequestFocus();
        }
    }//GEN-LAST:event_newTransactionMenuActionPerformed

    private void productsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsMenuItemActionPerformed

    private void addProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addProductMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private pointofsales.MainPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newTransactionMenu;
    private javax.swing.JMenuItem productsMenuItem;
    private javax.swing.JMenu transactionsButton;
    // End of variables declaration//GEN-END:variables
}
